name: All
on: [push]
jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
#          - os: ubuntu-latest
#            build-script: "build-dist.sh"
          - os: windows-latest
            build-script: "build-dist.ps1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build
        run: |
          ./${{ matrix.build-script }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: dist/
